routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name("welcome");

Auth::routes();

Route::group([
    'middleware' => ['auth'],
    'prefix'=> 'user'
], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/properties/pending', 'PropertyController@indexPending')->name('properties.pending');

    Route::delete('/properties/force-destroy/{property}', 'PropertyController@forceDestroy')
        ->where(['property' => '[0-9]+'])
        ->name('properties.forceDestroy');

    Route::delete('/properties/{property}/images/{image}', 'PropertyController@destroyImage')
        ->where([
            'property' => '[0-9]+',
            'image' => '[0-9]+',
            ])
        ->name('image.destroy');

    Route::get('/properties/{property}/images/{image}', 'PropertyController@setFeatureImage')
        ->where([
            'property' => '[0-9]+',
            'image' => '[0-9]+',
            ])
        ->name('image.set_featured');

    Route::get('/properties/{property}/images', 'PropertyController@addImage')
        ->where(['property' => '[0-9]+'])
        ->name('properties.add_image');

    Route::post('/properties/{property}/images', 'PropertyController@storeImage')
        ->where(['property' => '[0-9]+'])
        ->name('properties.store_image');

    Route::get('/properties/bookmarks', 'PropertyController@bookmarks_index')->name('bookmarks.index');
    Route::resource('/properties', 'PropertyController');
    Route::resource('/alertes', 'AlerteController');

});


// TEST
Route::get('/test', 'HomeController@test')->name('test');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    @include("layouts.includes.head")
</head>
<body id="body">
<!-- Preloader -->
<div id="preloader">
    <div class="south-load"></div>
</div>
@include("layouts.includes.nav")
@yield('app_content')
@include("layouts.includes.footer")
<!-- Scrips -->
@include("layouts.includes.footer-scripts")
</body>
</html>

resources/views/layouts/menu_app.blade.php
@extends('layouts.app')

@section('app_content')
    <div class="top_margin bottom_margin page_min_height" id="user_home_page">
        <div class="my_container">
            <div class="row">
                <div class="col-sm-3 col-md-3">
                    <div id="menu">
                        <button class="accordion menu_item">Proprietés</button>
                        <div class="panel">
                            <ul class="list-group">
                                <a href="{{ route('properties.create') }}" class="{{ currentRoute('properties.create') }}"><li class="list-group-item">Publier une annonce</li></a>
                                <a href="{{ route('properties.index') }}" class="{{ currentRoute('properties.index') }}"><li class="list-group-item">Annonces publiées</li></a>
                                <a href="{{ route('properties.pending') }}" class="{{ currentRoute('properties.pending') }}"><li class="list-group-item">Annonces en attente</li></a>
                                <a href="{{ route('bookmarks.index') }}" class="{{ currentRoute('bookmarks.index') }}"><li class="list-group-item">Mes favoris</li></a>
                            </ul>
                        </div>

                        <button class="accordion menu_item">Alertes</button>
                        <div class="panel">
                            <ul class="list-group">
                                <a href="{{ route('alertes.create') }}" class="{{ currentRoute('alertes.create') }}"><li class="list-group-item">Créer une alerte</li></a>
                                <a href="{{ route('alertes.index') }}" class="{{ currentRoute('alertes.index') }}"><li class="list-group-item">Mes alertes</li></a>
                            </ul>
                        </div>

                        <button class="accordion menu_item">Corbeille</button>
                    </div>
                </div>

                <div class="col-sm-9 col-md-9">
                    @yield('menu_app_content')
                </div>
            </div>
        </div>
    </div>
@endsection